name: QEMU Firmware Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libglib2.0-dev libpixman-1-dev wget

    - name: Download and install riscv32 toolchain
      run: |
        wget https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2024.01.21/riscv32-elf-ubuntu-22.04-nightly-2024.01.21.tar.gz
        tar -xzf riscv32-elf-ubuntu-22.04-nightly-2024.01.21.tar.gz
        echo "$PWD/riscv32-elf/bin" >> $GITHUB_PATH

    - name: Configure QEMU
      run: |
        mkdir build
        cd build
        ../configure --target-list=riscv32-softmmu --enable-debug --disable-user --disable-tools --disable-docs

    - name: Build QEMU
      run: |
        cd build
        make -j$(nproc)

    - name: Build firmware test
      run: |
        cd firmware-test
        make

    - name: Run QEMU firmware test
      run: |
        cd firmware-test
        chmod +x runQEMU
        ./runQEMU
