name: Run firmware tests in QEMU

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Init test submodule
        run: git submodule update --init firmware-tests

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libglib2.0-dev libpixman-1-dev wget tar xz-utils unzip

      - name: Cache Gaisler NCC Toolchain
        id: cache-ncc
        uses: actions/cache@v4
        with:
          path: ${{ env.HOME }}/gaisler/ncc
          key: ${{ runner.os }}-gaisler-ncc-1.0.4

      - name: Download and extract Gaisler NCC if not cached
        if: steps.cache-ncc.outputs.cache-hit != 'true'
        run: |
          mkdir -p $HOME/gaisler
          wget http://download.gaisler.com/products/ncc/bin/ncc-1.0.4-gcc-linux64.tar.xz -O ncc.tar.xz
          tar -xf ncc.tar.xz -C $HOME/gaisler
          mv $HOME/gaisler/ncc-* $HOME/gaisler/ncc

      - name: Add Gaisler NCC to PATH
        run: echo "$HOME/gaisler/ncc/bin" >> $GITHUB_PATH

      - name: Verify toolchain installation
        run: |
          ls -la $HOME/gaisler/ncc/bin
          which riscv-gaisler-elf-as

      - name: Cache QEMU build directory
        id: cache-qemu-build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-qemu-build-${{ hashFiles('**/configure', '**/Makefile') }}

      - name: Build QEMU (riscv32-softmmu only)
        run: |
          mkdir -p build
          cd build
          ../configure --target-list=riscv32-softmmu --enable-debug --disable-user --disable-tools --disable-docs
          make -j$(nproc)

      - name: Build firmware tests
        run: |
          cd firmware-tests
          make

      - name: Run QEMU uartTest
        run: |
          cd firmware-tests/
          chmod +x runQEMU
          echo "🧪 Running UART loopback test..."
          timeout 15s ./runQEMU uartTest | tee uart.log || true

      - name: Check loopback test result
        run: |
          cd firmware-tests/
          if grep -q "UART loopback test PASSED" uart.log; then
            echo "✅ Test PASSED"
          else
            echo "❌ UART loopback test failed"
            exit 1
          fi
      
      - name: Run QEMU gpioTest
        run: |
          cd firmware-tests/
          chmod +x runQEMU
          echo "🧪 Running GPIO test..."
          timeout 15s ./runQEMU gpioTest | tee gpio.log || true

      - name: Check GPIO test result
        run: |
          cd firmware-tests/
          if grep -q "GPIO test PASSED" gpio.log; then
            echo "✅ GPIO test PASSED"
          else
            echo "❌ GPIO test failed"
            exit 1
          fi

      - name: Run QEMU timerTest
        run: |
          cd firmware-tests/
          chmod +x runQEMU
          echo "🧪 Running Timer test..."
          timeout 15s ./runQEMU timerTest | tee timer.log || true

      - name: Check Timer test result
        run: |
          cd firmware-tests/
          if grep -q "Timer test PASSED" timer.log; then
            echo "✅ Timer test PASSED"
          else
            echo "❌ Timer test failed"
            exit 1
          fi
