name: Run firmware tests in QEMU

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libglib2.0-dev libpixman-1-dev wget

    # Cache Gaisler NCC toolchain
    - name: Cache Gaisler NCC Toolchain
      id: cache-ncc
      uses: actions/cache@v4
      with:
        path: /opt/gaisler
        key: gaisler-ncc-1.0.4

    - name: Download and extract Gaisler NCC
      if: steps.cache-ncc.outputs.cache-hit != 'true'
      run: |
        wget http://download.gaisler.com/products/ncc/bin/ncc-1.0.4-gcc-mingw64.zip -O gaisler.zip
        sudo unzip -q gaisler.zip -d /opt/gaisler

    - name: Add Gaisler NCC to PATH
      run: echo "/opt/gaisler/ncc-1.0.4-gcc-mingw64/bin" >> $GITHUB_PATH

    # Compilar QEMU
    - name: Build QEMU (riscv32-softmmu only)
      run: |
        mkdir -p build
        cd build
        ../configure --target-list=riscv32-softmmu --enable-debug --disable-user --disable-tools --disable-docs
        make -j$(nproc)

    # Compilar firmware test
    - name: Build firmware tests
      run: |
        cd firmware-test
        make

    # Ejecutar test con QEMU
    - name: Run QEMU tests
      run: |
        cd firmware-test
        chmod +x ./runQEMU
        ./runQEMU
 
